cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'bash'
brew 'ack'
brew 'coreutils'
brew 'go'
brew 'python'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'youtube-dl'
brew 'arp-scan'
brew 'gnupg'
brew 'gnuradio'
brew 'hackrf'
brew 'nmap'
brew 'ircii'
brew 'tmux'
brew 'siege'
brew 'stoken'
brew 'qrencode'
brew 'ngrep'

cask 'lastpass'
cask 'adium'
cask 'firefox'
cask 'google-chrome'
cask 'handbrake'
cask 'seashore'
cask 'slack'
cask 'steam'
cask 'transmission'
cask 'viscosity'
cask 'vlc'
cask 'filezilla'
cask 'torbrowser'
cask 'chirp'
cask 'notational-velocity'
cask 'spotify'
cask 'skype'
